# Generated by Django 3.0.14 on 2022-04-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
