# Generated by Django 3.0.14 on 2022-04-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20220407_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Collectables_Art', 'Collectables & Art'), ('Home_Garden', 'Home & Garden'), ('Clothing_Shoes_Accessories', 'Clothing, Shoes & Accessories'), ('Toys_Hobbies', 'Toys & Hobbies'), ('Sporting Goods', 'Sporting Goods'), ('Books_Movies_Music', 'Books, Movies & Music'), ('Health_Beauty', 'Health & Beauty'), ('Buisness_Industrial', 'Buisness & Industrial'), ('Jewelry_Watches', 'Jewelry & Watches'), ('Baby Essentials', 'Baby Essentials'), ('Pet_Supplies', 'Pet Supplies'), ('Pet', 'Pet'), ('Other', 'Other')], max_length=200),
        ),
    ]
